StJohnEPAD/StJohnEPAD/Controllers/DutyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StJohnEPAD.Models;
using StJohnEPAD.DAL;

namespace StJohnEPAD.Controllers
{
    public class DutyController : Controller
    {
        private SJAContext db = new SJAContext();

        //
        // GET: /Duty/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewAll()
        {
            return View(db.Duties.ToList());
        }

        //
        // GET: /Duty/Details/5

        public ActionResult Details(int id = 0)
        {
            Duty duty = db.Duties.Find(id);
            if (duty == null)
            {
                return HttpNotFound();
            }
            return View(duty);
        }

        //
        // GET: /Duty/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Duty/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Duty duty)
        {
            if (ModelState.IsValid)
            {
                db.Duties.Add(duty);
                db.SaveChanges();
                return RedirectToAction("ViewAll");
            }

            return View(duty);
        }

        //
        // GET: /Duty/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Duty duty = db.Duties.Find(id);
            if (duty == null)
            {
                return HttpNotFound();
            }
            return View(duty);
        }

        //
        // POST: /Duty/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Duty duty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(duty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViewAll");
            }
            return View(duty);
        }

        //
        // GET: /Duty/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Duty duty = db.Duties.Find(id);
            if (duty == null)
            {
                return HttpNotFound();
            }
            return View(duty);
        }

        //
        // POST: /Duty/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Duty duty = db.Duties.Find(id);
            db.Duties.Remove(duty);
            db.SaveChanges();
            return RedirectToAction("ViewAll");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

StJohnEPAD/StJohnEPAD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - St John Ambulance EPaD</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">
                        <a href="@Url.Action("Index","Home")"><img src="@Url.Content("~/Images/SJA-device-60.jpg")" alt="St John Ambulance" /></a>
                    </p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @if (Request.IsAuthenticated) {
                            <text>
                                Logged in as @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "username", title = "Manage" })
                            </text>
                        }
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <!--- login / logout section -->
                            @if (Request.IsAuthenticated) {
                                <text>
                                <li>@Html.ActionLink("Duties", "Index", "Duty")</li>
                                <li> @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" })) {
                                    @Html.AntiForgeryToken()
                                    <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
                                    }
                                </li>
                                </text>
                            } else {
                                <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                            }
                            <!--end login-->


                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - 18 Technology</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>